---
- name: Extra Variables Example
  hosts: all
  become: true

  vars:
    package_name: nginx

  tasks:

    - name: Install Package
      ansible.builtin.package:
        name: "{{ package_name }}"
        state: present

    - name: Display Package Name
      ansible.builtin.debug:
        msg: "Installed package: {{ package_name }}"
