---
- name: Registered Variables Example
  hosts: all
  become: true

  tasks:

    - name: Check Disk Usage
      ansible.builtin.command: df -h
      register: disk_output
      changed_when: false

    - name: Check Memory Usage
      ansible.builtin.command: free -h
      register: memory_output
      changed_when: false

    - name: Check Uptime
      ansible.builtin.command: uptime
      register: uptime_output
      changed_when: false

    - name: Display Disk Usage
      ansible.builtin.debug:
        var: disk_output.stdout_lines

    - name: Display Memory Usage
      ansible.builtin.debug:
        var: memory_output.stdout_lines

    - name: Display Uptime
      ansible.builtin.debug:
        var: uptime_output.stdout
