---
- name: Deploy Basic Template
  hosts: webservers
  become: true

  tasks:

    - name: Deploy HTML Template
      ansible.builtin.template:
        src: templates/index.html.j2
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: "0644"

    - name: Display Success Message
      ansible.builtin.debug:
        msg: "Template deployed successfully."
