---
- name: Template with Handler
  hosts: webservers
  become: true

  tasks:

    - name: Deploy Nginx Configuration
      ansible.builtin.template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: "0644"
      notify:
        - Restart Nginx

  handlers:

    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
