---
- name: Install Docker
  ansible.builtin.apt:
    name: docker.io
    state: present
    update_cache: true

- name: Start and enable Docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Add users to Docker group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop: "{{ docker_users }}"

- name: Check Docker version
  ansible.builtin.command:
    cmd: docker --version
  register: docker_version
  changed_when: false

- name: Display Docker version
  ansible.builtin.debug:
    var: docker_version.stdout
